### ISSUE TITLE
jobLogger不能打印日志

### ISSUE THREAD

**Issue by dudylan** [Aouchinx/xxl-job-executor-nodejs#1]
使用example jobhandler jobLogger不能打印日志
xxl-job-admin 版本为2.3.1-SNAPSHOT

**Comment by OU8N** [comment]
> 

很久没更新了，空了我push个新版本再试试

**Comment by OU8N** [comment]
> 使用example jobhandler jobLogger不能打印日志 xxl-job-admin 版本为2.3.1-SNAPSHOT

@dudylan  你更新下再试试

**Comment by OU8N** [comment]
暂时关闭，有新的问题可以继续反馈
